use_frameworks!

target 'Push Notification Registration' do
  pod 'Cycle', :path => '../'
  target 'Cycle_Tests' do
    inherit! :search_paths
  end
end

target 'Shortcut Items' do
  pod 'Cycle', :path => '../'
end

target 'Integer Mutation' do
  pod 'Cycle', :path => '../'
  pod 'RxCocoa', '~> 3.5.0'
end

target 'URL Action Outgoing' do
  pod 'Cycle', :path => '../'
end
